export const QUERY_KEYS = {
  fetch_datasets: "fetch-datasets",
  fetch_dataset: "fetch-dataset",
  fetch_column: "fetch-column",
  fetch_binance_tickers: "fetch-binance-tickers",
  fetch_datasets_models: "fetch-datasets-models",
  fetch_dataset_model_by_name: "fetch-dataset-model-by-name",
  fetch_all_model_training_metadata: "fetch-all-model-training-metadata",
  fetch_train_job_detailed: "fetch_train_job_detailed",
  fetch_trainjob_backtests: "fetch_train_job_backtests",
  fetch_dataset_backtests: "fetch_dataset_backtests",
  fetch_backtest_by_id: "fetch_backtest_by_id",
  fetch_code_presets: "fetch_code_presets",
  fetch_mass_backtests_by_id: "fetch_mass_backtests_by_id",
  fetch_mass_backtest: "fetch_mass_backtest",
  fetch_many_backtests_by_id: "fetch_many_backtests_by_id",
  fetch_data_transformations: "fetch_data_transformations",
  fetch_long_short_backtests: "fetch_long_short_backtests",
  fetch_epoch_validation_preds: "fetch_epoch_validation_preds",
  fetch_ml_models_cols: "fetch_ml_models_cols",
  fetch_mass_backtest_symbols: "fetch_mass_backtest_symbols",
  fetch_mass_backtest_transformations: "fetch_mass_backtest_transformations",
  fetch_nyse_symbols: "fetch_nyse_symbols",
};
