"""Add trading fees perc to backtest schema

Revision ID: 2e25b951616d
Revises: dda6186dc279
Create Date: 2024-04-18 12:39:50.915822

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2e25b951616d'
down_revision: Union[str, None] = 'dda6186dc279'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('backtest', sa.Column('trading_fees_perc', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('backtest', 'trading_fees_perc')
    # ### end Alembic commands ###
