"""Simplify backtest schema

Revision ID: 4eabda67e62c
Revises: 186e88800643
Create Date: 2024-04-17 16:54:05.748936

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4eabda67e62c'
down_revision: Union[str, None] = '186e88800643'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('backtest', sa.Column('open_trade_cond', sa.String(), nullable=True))
    op.add_column('backtest', sa.Column('close_trade_cond', sa.String(), nullable=True))
    op.add_column('backtest', sa.Column('is_short_selling_strategy', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('backtest', 'is_short_selling_strategy')
    op.drop_column('backtest', 'close_trade_cond')
    op.drop_column('backtest', 'open_trade_cond')
    # ### end Alembic commands ###
