"""Create mass backtest schema

Revision ID: 5398c74255b5
Revises: f1b1ab7329e7
Create Date: 2024-04-18 08:34:02.561516

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5398c74255b5'
down_revision: Union[str, None] = 'f1b1ab7329e7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('backtest', sa.Column('slippage_perc', sa.Float(), nullable=True))
    op.add_column('backtest', sa.Column('short_fee_hourly', sa.Float(), nullable=True))
    op.add_column('mass_backtest', sa.Column('backtest_ids', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('mass_backtest', 'backtest_ids')
    op.drop_column('backtest', 'short_fee_hourly')
    op.drop_column('backtest', 'slippage_perc')
    # ### end Alembic commands ###
