"""Add description field to code_presets table

Revision ID: 5eeb569bb8a8
Revises: baccf8185c78
Create Date: 2024-04-22 19:04:25.796515

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5eeb569bb8a8'
down_revision: Union[str, None] = 'baccf8185c78'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('code_preset', sa.Column('description', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('code_preset', 'description')
    # ### end Alembic commands ###
