"""Upgrade schema

Revision ID: 14916fa938b2
Revises: df98eb59d832
Create Date: 2024-04-28 20:40:58.968574

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '14916fa938b2'
down_revision: Union[str, None] = 'df98eb59d832'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('backtest_history', sa.Column('debt_to_net_value_ratio', sa.Float(), nullable=True))
    op.add_column('backtest_history', sa.Column('total_debt', sa.Float(), nullable=True))
    op.add_column('backtest_history', sa.Column('total_long', sa.Float(), nullable=True))
    op.add_column('backtest_statistics', sa.Column('long_side_profit_factor', sa.Float(), nullable=True))
    op.add_column('backtest_statistics', sa.Column('short_side_profit_factor', sa.Float(), nullable=True))
    op.alter_column('data_transformation', 'dataset_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('data_transformation', 'dataset_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('backtest_statistics', 'short_side_profit_factor')
    op.drop_column('backtest_statistics', 'long_side_profit_factor')
    op.drop_column('backtest_history', 'total_long')
    op.drop_column('backtest_history', 'total_debt')
    op.drop_column('backtest_history', 'debt_to_net_value_ratio')
    # ### end Alembic commands ###
