"""Add candle interval field

Revision ID: dda6186dc279
Revises: e0934fc09e8b
Create Date: 2024-04-18 09:20:22.312274

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dda6186dc279'
down_revision: Union[str, None] = 'e0934fc09e8b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('backtest', sa.Column('candle_interval', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('backtest', 'candle_interval')
    # ### end Alembic commands ###
