"""Temporary delete kline_delta_time_ms

Revision ID: e0934fc09e8b
Revises: 5398c74255b5
Create Date: 2024-04-18 09:17:58.372146

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e0934fc09e8b'
down_revision: Union[str, None] = '5398c74255b5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('backtest', 'kline_time_delta_ms')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('backtest', sa.Column('kline_time_delta_ms', sa.INTEGER(), nullable=True))
    # ### end Alembic commands ###
