"""Add candle time delta to backtest schema

Revision ID: f1b1ab7329e7
Revises: 4eabda67e62c
Create Date: 2024-04-17 21:07:40.887872

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f1b1ab7329e7'
down_revision: Union[str, None] = '4eabda67e62c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('backtest', sa.Column('kline_time_delta_ms', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('backtest', 'kline_time_delta_ms')
    # ### end Alembic commands ###
